export const dashboardOverview = {
  welcomeUser: 'Biswanath',
  businessName: 'Fitryx',
  periodLabel: 'Last 30 Days',
  heroStats: [
    { label: 'Revenue', value: '\u20B949,900', tone: 'emerald' },
    { label: 'Active Members', value: '24', tone: 'blue' },
    { label: 'Renewals', value: '16', tone: 'indigo' },
  ],
  snapshot: [
    { label: 'Check-ins', value: '0', tone: 'emerald', icon: 'trendUp' },
    { label: 'Check-outs', value: '0', tone: 'slate', icon: 'trendDown' },
    { label: 'Currently In', value: '0', tone: 'blue', icon: 'users' },
    { label: 'Classes', value: '0/4', tone: 'indigo', icon: 'calendar' },
    { label: 'PT Sessions', value: '0', tone: 'violet', icon: 'dumbbell' },
    { label: 'Payments', value: '\u20B90', tone: 'emerald', icon: 'card' },
  ],
  kpis: [
    {
      label: 'Total Revenue',
      value: '\u20B949,900',
      detail: 'From 35 transactions',
      change: '+100.0%',
      changeType: 'positive',
      tone: 'emerald',
      icon: 'revenue',
    },
    {
      label: 'Active Members',
      value: '24',
      detail: 'of 26 total members',
      change: '+19',
      changeType: 'positive',
      tone: 'blue',
      icon: 'users',
      progress: 92,
    },
    {
      label: 'New Members',
      value: '19',
      detail: 'Joined this period',
      change: '+16',
      changeType: 'positive',
      tone: 'indigo',
      icon: 'userPlus',
    },
    {
      label: 'Renewals',
      value: '16',
      detail: '+\u20B930,000 revenue',
      change: '+16',
      changeType: 'positive',
      tone: 'teal',
      icon: 'refresh',
    },
    {
      label: 'Expiring Soon',
      value: '2',
      detail: 'Expiring in next 7 days',
      tone: 'amber',
      icon: 'alert',
    },
    {
      label: 'Pending Leads',
      value: '5',
      detail: 'Awaiting follow-up',
      badge: '5 due',
      tone: 'rose',
      icon: 'userPlus',
    },
    {
      label: 'Period Attendance',
      value: '20',
      detail: '1 avg daily',
      tone: 'emerald',
      icon: 'check',
    },
    {
      label: 'PT Sessions',
      value: '18',
      detail: '\u20B910,000 revenue',
      tone: 'blue',
      icon: 'dumbbell',
    },
  ],
  revenueOverview: {
    total: '\u20B959,900',
    subtitle: 'Last 30 Days',
    data: [
      { label: '13 Jan', revenue: 0, comparison: 0 },
      { label: '15 Jan', revenue: 0, comparison: 0 },
      { label: '17 Jan', revenue: 0, comparison: 0 },
      { label: '19 Jan', revenue: 12500, comparison: 9200 },
      { label: '21 Jan', revenue: 0, comparison: 0 },
      { label: '23 Jan', revenue: 6100, comparison: 0 },
      { label: '25 Jan', revenue: 0, comparison: 0 },
      { label: '27 Jan', revenue: 0, comparison: 0 },
      { label: '29 Jan', revenue: 0, comparison: 0 },
      { label: '31 Jan', revenue: 3600, comparison: 3100 },
      { label: '2 Feb', revenue: 2800, comparison: 2500 },
      { label: '4 Feb', revenue: 0, comparison: 0 },
      { label: '6 Feb', revenue: 10800, comparison: 7800 },
      { label: '8 Feb', revenue: 1600, comparison: 1200 },
      { label: '11 Feb', revenue: 0, comparison: 0 },
    ],
  },
  membershipDistribution: [
    { name: 'Basic', value: 412, color: '#94A3B8' },
    { name: 'Premium', value: 624, color: '#6C63FF' },
    { name: 'Elite', value: 212, color: '#22C55E' },
  ],
  peakHours: [
    { time: '6AM', value: 180 },
    { time: '9AM', value: 120 },
    { time: '12PM', value: 160 },
    { time: '3PM', value: 90 },
    { time: '6PM', value: 280 },
    { time: '9PM', value: 110 },
  ],
  attentionItems: [
    {
      title: '5 leads awaiting follow-up',
      description: '5 follow-ups overdue and ready for the sales team.',
      action: 'Follow Up Now',
      badge: 'Sales',
      tone: 'blue',
      icon: 'userPlus',
    },
    {
      title: '2 PT members need trainer assignment',
      description: 'Assign trainers to keep onboarding moving this week.',
      action: 'Assign Now',
      badge: 'PT',
      tone: 'amber',
      icon: 'dumbbell',
    },
    {
      title: '3 memberships expiring this week',
      description: 'Reach out early to improve renewals before they lapse.',
      action: 'Review Renewals',
      badge: 'Renewals',
      tone: 'indigo',
      icon: 'clock',
    },
  ],
};
